// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: activity_api/activity.proto

package activity_api

import (
	models "github.com/Sol1tud9/taskflow/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	FromTimestamp int64                  `protobuf:"varint,3,opt,name=from_timestamp,json=fromTimestamp,proto3" json:"from_timestamp,omitempty"`
	ToTimestamp   int64                  `protobuf:"varint,4,opt,name=to_timestamp,json=toTimestamp,proto3" json:"to_timestamp,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivitiesRequest) Reset() {
	*x = GetActivitiesRequest{}
	mi := &file_activity_api_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivitiesRequest) ProtoMessage() {}

func (x *GetActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_api_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivitiesRequest.ProtoReflect.Descriptor instead.
func (*GetActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_activity_api_activity_proto_rawDescGZIP(), []int{0}
}

func (x *GetActivitiesRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *GetActivitiesRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *GetActivitiesRequest) GetFromTimestamp() int64 {
	if x != nil {
		return x.FromTimestamp
	}
	return 0
}

func (x *GetActivitiesRequest) GetToTimestamp() int64 {
	if x != nil {
		return x.ToTimestamp
	}
	return 0
}

func (x *GetActivitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetActivitiesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*models.Activity     `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivitiesResponse) Reset() {
	*x = GetActivitiesResponse{}
	mi := &file_activity_api_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivitiesResponse) ProtoMessage() {}

func (x *GetActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_api_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivitiesResponse.ProtoReflect.Descriptor instead.
func (*GetActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_activity_api_activity_proto_rawDescGZIP(), []int{1}
}

func (x *GetActivitiesResponse) GetActivities() []*models.Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *GetActivitiesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetUserActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromTimestamp int64                  `protobuf:"varint,2,opt,name=from_timestamp,json=fromTimestamp,proto3" json:"from_timestamp,omitempty"`
	ToTimestamp   int64                  `protobuf:"varint,3,opt,name=to_timestamp,json=toTimestamp,proto3" json:"to_timestamp,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActivitiesRequest) Reset() {
	*x = GetUserActivitiesRequest{}
	mi := &file_activity_api_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActivitiesRequest) ProtoMessage() {}

func (x *GetUserActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_api_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActivitiesRequest.ProtoReflect.Descriptor instead.
func (*GetUserActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_activity_api_activity_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserActivitiesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserActivitiesRequest) GetFromTimestamp() int64 {
	if x != nil {
		return x.FromTimestamp
	}
	return 0
}

func (x *GetUserActivitiesRequest) GetToTimestamp() int64 {
	if x != nil {
		return x.ToTimestamp
	}
	return 0
}

func (x *GetUserActivitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserActivitiesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUserActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*models.Activity     `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActivitiesResponse) Reset() {
	*x = GetUserActivitiesResponse{}
	mi := &file_activity_api_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActivitiesResponse) ProtoMessage() {}

func (x *GetUserActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_api_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActivitiesResponse.ProtoReflect.Descriptor instead.
func (*GetUserActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_activity_api_activity_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserActivitiesResponse) GetActivities() []*models.Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *GetUserActivitiesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_activity_api_activity_proto protoreflect.FileDescriptor

const file_activity_api_activity_proto_rawDesc = "" +
	"\n" +
	"\x1bactivity_api/activity.proto\x12\x14taskflow.activity.v1\x1a\x15models/activity.proto\x1a\x1cgoogle/api/annotations.proto\"\xcc\x01\n" +
	"\x14GetActivitiesRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12%\n" +
	"\x0efrom_timestamp\x18\x03 \x01(\x03R\rfromTimestamp\x12!\n" +
	"\fto_timestamp\x18\x04 \x01(\x03R\vtoTimestamp\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"k\n" +
	"\x15GetActivitiesResponse\x12<\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x1c.taskflow.models.v1.ActivityR\n" +
	"activities\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xab\x01\n" +
	"\x18GetUserActivitiesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0efrom_timestamp\x18\x02 \x01(\x03R\rfromTimestamp\x12!\n" +
	"\fto_timestamp\x18\x03 \x01(\x03R\vtoTimestamp\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"o\n" +
	"\x19GetUserActivitiesResponse\x12<\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x1c.taskflow.models.v1.ActivityR\n" +
	"activities\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xbb\x02\n" +
	"\x0fActivityService\x12\x84\x01\n" +
	"\rGetActivities\x12*.taskflow.activity.v1.GetActivitiesRequest\x1a+.taskflow.activity.v1.GetActivitiesResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/activities\x12\xa0\x01\n" +
	"\x11GetUserActivities\x12..taskflow.activity.v1.GetUserActivitiesRequest\x1a/.taskflow.activity.v1.GetUserActivitiesResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/users/{user_id}/activitiesB7Z5github.com/Sol1tud9/taskflow/internal/pb/activity_apib\x06proto3"

var (
	file_activity_api_activity_proto_rawDescOnce sync.Once
	file_activity_api_activity_proto_rawDescData []byte
)

func file_activity_api_activity_proto_rawDescGZIP() []byte {
	file_activity_api_activity_proto_rawDescOnce.Do(func() {
		file_activity_api_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_api_activity_proto_rawDesc), len(file_activity_api_activity_proto_rawDesc)))
	})
	return file_activity_api_activity_proto_rawDescData
}

var file_activity_api_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_activity_api_activity_proto_goTypes = []any{
	(*GetActivitiesRequest)(nil),      // 0: taskflow.activity.v1.GetActivitiesRequest
	(*GetActivitiesResponse)(nil),     // 1: taskflow.activity.v1.GetActivitiesResponse
	(*GetUserActivitiesRequest)(nil),  // 2: taskflow.activity.v1.GetUserActivitiesRequest
	(*GetUserActivitiesResponse)(nil), // 3: taskflow.activity.v1.GetUserActivitiesResponse
	(*models.Activity)(nil),           // 4: taskflow.models.v1.Activity
}
var file_activity_api_activity_proto_depIdxs = []int32{
	4, // 0: taskflow.activity.v1.GetActivitiesResponse.activities:type_name -> taskflow.models.v1.Activity
	4, // 1: taskflow.activity.v1.GetUserActivitiesResponse.activities:type_name -> taskflow.models.v1.Activity
	0, // 2: taskflow.activity.v1.ActivityService.GetActivities:input_type -> taskflow.activity.v1.GetActivitiesRequest
	2, // 3: taskflow.activity.v1.ActivityService.GetUserActivities:input_type -> taskflow.activity.v1.GetUserActivitiesRequest
	1, // 4: taskflow.activity.v1.ActivityService.GetActivities:output_type -> taskflow.activity.v1.GetActivitiesResponse
	3, // 5: taskflow.activity.v1.ActivityService.GetUserActivities:output_type -> taskflow.activity.v1.GetUserActivitiesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_activity_api_activity_proto_init() }
func file_activity_api_activity_proto_init() {
	if File_activity_api_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_api_activity_proto_rawDesc), len(file_activity_api_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_activity_api_activity_proto_goTypes,
		DependencyIndexes: file_activity_api_activity_proto_depIdxs,
		MessageInfos:      file_activity_api_activity_proto_msgTypes,
	}.Build()
	File_activity_api_activity_proto = out.File
	file_activity_api_activity_proto_goTypes = nil
	file_activity_api_activity_proto_depIdxs = nil
}
