// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: models/activity.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Activity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_models_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_models_activity_proto_rawDescGZIP(), []int{0}
}

func (x *Activity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Activity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Activity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Activity) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Activity) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Activity) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Activity) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_models_activity_proto protoreflect.FileDescriptor

const file_models_activity_proto_rawDesc = "" +
	"\n" +
	"\x15models/activity.proto\x12\x12taskflow.models.v1\"\xc4\x01\n" +
	"\bActivity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\tR\bentityId\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAtB1Z/github.com/Sol1tud9/taskflow/internal/pb/modelsb\x06proto3"

var (
	file_models_activity_proto_rawDescOnce sync.Once
	file_models_activity_proto_rawDescData []byte
)

func file_models_activity_proto_rawDescGZIP() []byte {
	file_models_activity_proto_rawDescOnce.Do(func() {
		file_models_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_activity_proto_rawDesc), len(file_models_activity_proto_rawDesc)))
	})
	return file_models_activity_proto_rawDescData
}

var file_models_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_activity_proto_goTypes = []any{
	(*Activity)(nil), // 0: taskflow.models.v1.Activity
}
var file_models_activity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_activity_proto_init() }
func file_models_activity_proto_init() {
	if File_models_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_activity_proto_rawDesc), len(file_models_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_activity_proto_goTypes,
		DependencyIndexes: file_models_activity_proto_depIdxs,
		MessageInfos:      file_models_activity_proto_msgTypes,
	}.Build()
	File_models_activity_proto = out.File
	file_models_activity_proto_goTypes = nil
	file_models_activity_proto_depIdxs = nil
}
