// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: models/task.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	AssigneeId    string                 `protobuf:"bytes,6,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	CreatorId     string                 `protobuf:"bytes,7,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,8,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	DueDate       int64                  `protobuf:"varint,9,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_models_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_models_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_models_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Task) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *Task) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Task) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Task) GetDueDate() int64 {
	if x != nil {
		return x.DueDate
	}
	return 0
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type TaskHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Field         string                 `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"`
	OldValue      string                 `protobuf:"bytes,5,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue      string                 `protobuf:"bytes,6,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	ChangedAt     int64                  `protobuf:"varint,7,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskHistory) Reset() {
	*x = TaskHistory{}
	mi := &file_models_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskHistory) ProtoMessage() {}

func (x *TaskHistory) ProtoReflect() protoreflect.Message {
	mi := &file_models_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskHistory.ProtoReflect.Descriptor instead.
func (*TaskHistory) Descriptor() ([]byte, []int) {
	return file_models_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskHistory) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskHistory) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TaskHistory) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *TaskHistory) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

func (x *TaskHistory) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

func (x *TaskHistory) GetChangedAt() int64 {
	if x != nil {
		return x.ChangedAt
	}
	return 0
}

var File_models_task_proto protoreflect.FileDescriptor

const file_models_task_proto_rawDesc = "" +
	"\n" +
	"\x11models/task.proto\x12\x12taskflow.models.v1\"\xb4\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x1f\n" +
	"\vassignee_id\x18\x06 \x01(\tR\n" +
	"assigneeId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\a \x01(\tR\tcreatorId\x12\x17\n" +
	"\ateam_id\x18\b \x01(\tR\x06teamId\x12\x19\n" +
	"\bdue_date\x18\t \x01(\x03R\adueDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\xbe\x01\n" +
	"\vTaskHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05field\x18\x04 \x01(\tR\x05field\x12\x1b\n" +
	"\told_value\x18\x05 \x01(\tR\boldValue\x12\x1b\n" +
	"\tnew_value\x18\x06 \x01(\tR\bnewValue\x12\x1d\n" +
	"\n" +
	"changed_at\x18\a \x01(\x03R\tchangedAtB1Z/github.com/Sol1tud9/taskflow/internal/pb/modelsb\x06proto3"

var (
	file_models_task_proto_rawDescOnce sync.Once
	file_models_task_proto_rawDescData []byte
)

func file_models_task_proto_rawDescGZIP() []byte {
	file_models_task_proto_rawDescOnce.Do(func() {
		file_models_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_task_proto_rawDesc), len(file_models_task_proto_rawDesc)))
	})
	return file_models_task_proto_rawDescData
}

var file_models_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_task_proto_goTypes = []any{
	(*Task)(nil),        // 0: taskflow.models.v1.Task
	(*TaskHistory)(nil), // 1: taskflow.models.v1.TaskHistory
}
var file_models_task_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_task_proto_init() }
func file_models_task_proto_init() {
	if File_models_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_task_proto_rawDesc), len(file_models_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_task_proto_goTypes,
		DependencyIndexes: file_models_task_proto_depIdxs,
		MessageInfos:      file_models_task_proto_msgTypes,
	}.Build()
	File_models_task_proto = out.File
	file_models_task_proto_goTypes = nil
	file_models_task_proto_depIdxs = nil
}
