// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: user_api/user.proto

package user_api

import (
	models "github.com/Sol1tud9/taskflow/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_api_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *models.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_api_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetUser() *models.User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_api_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *models.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_api_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetUser() *models.User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_api_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *models.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_api_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserResponse) GetUser() *models.User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_user_api_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type CreateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *models.Team           `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	mi := &file_user_api_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTeamResponse) GetTeam() *models.Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_user_api_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *models.Team           `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamResponse) Reset() {
	*x = GetTeamResponse{}
	mi := &file_user_api_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamResponse) ProtoMessage() {}

func (x *GetTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamResponse.ProtoReflect.Descriptor instead.
func (*GetTeamResponse) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetTeamResponse) GetTeam() *models.Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type AddTeamMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamMemberRequest) Reset() {
	*x = AddTeamMemberRequest{}
	mi := &file_user_api_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamMemberRequest) ProtoMessage() {}

func (x *AddTeamMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamMemberRequest.ProtoReflect.Descriptor instead.
func (*AddTeamMemberRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{10}
}

func (x *AddTeamMemberRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *AddTeamMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddTeamMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AddTeamMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *models.TeamMember     `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamMemberResponse) Reset() {
	*x = AddTeamMemberResponse{}
	mi := &file_user_api_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamMemberResponse) ProtoMessage() {}

func (x *AddTeamMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamMemberResponse.ProtoReflect.Descriptor instead.
func (*AddTeamMemberResponse) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{11}
}

func (x *AddTeamMemberResponse) GetMember() *models.TeamMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type GetTeamMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamMembersRequest) Reset() {
	*x = GetTeamMembersRequest{}
	mi := &file_user_api_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamMembersRequest) ProtoMessage() {}

func (x *GetTeamMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamMembersRequest.ProtoReflect.Descriptor instead.
func (*GetTeamMembersRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetTeamMembersRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetTeamMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*models.TeamMember   `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamMembersResponse) Reset() {
	*x = GetTeamMembersResponse{}
	mi := &file_user_api_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamMembersResponse) ProtoMessage() {}

func (x *GetTeamMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamMembersResponse.ProtoReflect.Descriptor instead.
func (*GetTeamMembersResponse) Descriptor() ([]byte, []int) {
	return file_user_api_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetTeamMembersResponse) GetMembers() []*models.TeamMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_user_api_user_proto protoreflect.FileDescriptor

const file_user_api_user_proto_rawDesc = "" +
	"\n" +
	"\x13user_api/user.proto\x12\x10taskflow.user.v1\x1a\x11models/user.proto\x1a\x1cgoogle/api/annotations.proto\"=\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"B\n" +
	"\x12CreateUserResponse\x12,\n" +
	"\x04user\x18\x01 \x01(\v2\x18.taskflow.models.v1.UserR\x04user\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x0fGetUserResponse\x12,\n" +
	"\x04user\x18\x01 \x01(\v2\x18.taskflow.models.v1.UserR\x04user\"M\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"B\n" +
	"\x12UpdateUserResponse\x12,\n" +
	"\x04user\x18\x01 \x01(\v2\x18.taskflow.models.v1.UserR\x04user\"B\n" +
	"\x11CreateTeamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"B\n" +
	"\x12CreateTeamResponse\x12,\n" +
	"\x04team\x18\x01 \x01(\v2\x18.taskflow.models.v1.TeamR\x04team\" \n" +
	"\x0eGetTeamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x0fGetTeamResponse\x12,\n" +
	"\x04team\x18\x01 \x01(\v2\x18.taskflow.models.v1.TeamR\x04team\"\\\n" +
	"\x14AddTeamMemberRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"O\n" +
	"\x15AddTeamMemberResponse\x126\n" +
	"\x06member\x18\x01 \x01(\v2\x1e.taskflow.models.v1.TeamMemberR\x06member\"0\n" +
	"\x15GetTeamMembersRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"R\n" +
	"\x16GetTeamMembersResponse\x128\n" +
	"\amembers\x18\x01 \x03(\v2\x1e.taskflow.models.v1.TeamMemberR\amembers2\xe1\x06\n" +
	"\vUserService\x12q\n" +
	"\n" +
	"CreateUser\x12#.taskflow.user.v1.CreateUserRequest\x1a$.taskflow.user.v1.CreateUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12j\n" +
	"\aGetUser\x12 .taskflow.user.v1.GetUserRequest\x1a!.taskflow.user.v1.GetUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/users/{id}\x12v\n" +
	"\n" +
	"UpdateUser\x12#.taskflow.user.v1.UpdateUserRequest\x1a$.taskflow.user.v1.UpdateUserResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*2\x12/api/v1/users/{id}\x12q\n" +
	"\n" +
	"CreateTeam\x12#.taskflow.user.v1.CreateTeamRequest\x1a$.taskflow.user.v1.CreateTeamResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/teams\x12j\n" +
	"\aGetTeam\x12 .taskflow.user.v1.GetTeamRequest\x1a!.taskflow.user.v1.GetTeamResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/teams/{id}\x12\x8c\x01\n" +
	"\rAddTeamMember\x12&.taskflow.user.v1.AddTeamMemberRequest\x1a'.taskflow.user.v1.AddTeamMemberResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/teams/{team_id}/members\x12\x8c\x01\n" +
	"\x0eGetTeamMembers\x12'.taskflow.user.v1.GetTeamMembersRequest\x1a(.taskflow.user.v1.GetTeamMembersResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/teams/{team_id}/membersB3Z1github.com/Sol1tud9/taskflow/internal/pb/user_apib\x06proto3"

var (
	file_user_api_user_proto_rawDescOnce sync.Once
	file_user_api_user_proto_rawDescData []byte
)

func file_user_api_user_proto_rawDescGZIP() []byte {
	file_user_api_user_proto_rawDescOnce.Do(func() {
		file_user_api_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_api_user_proto_rawDesc), len(file_user_api_user_proto_rawDesc)))
	})
	return file_user_api_user_proto_rawDescData
}

var file_user_api_user_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_user_api_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),      // 0: taskflow.user.v1.CreateUserRequest
	(*CreateUserResponse)(nil),     // 1: taskflow.user.v1.CreateUserResponse
	(*GetUserRequest)(nil),         // 2: taskflow.user.v1.GetUserRequest
	(*GetUserResponse)(nil),        // 3: taskflow.user.v1.GetUserResponse
	(*UpdateUserRequest)(nil),      // 4: taskflow.user.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),     // 5: taskflow.user.v1.UpdateUserResponse
	(*CreateTeamRequest)(nil),      // 6: taskflow.user.v1.CreateTeamRequest
	(*CreateTeamResponse)(nil),     // 7: taskflow.user.v1.CreateTeamResponse
	(*GetTeamRequest)(nil),         // 8: taskflow.user.v1.GetTeamRequest
	(*GetTeamResponse)(nil),        // 9: taskflow.user.v1.GetTeamResponse
	(*AddTeamMemberRequest)(nil),   // 10: taskflow.user.v1.AddTeamMemberRequest
	(*AddTeamMemberResponse)(nil),  // 11: taskflow.user.v1.AddTeamMemberResponse
	(*GetTeamMembersRequest)(nil),  // 12: taskflow.user.v1.GetTeamMembersRequest
	(*GetTeamMembersResponse)(nil), // 13: taskflow.user.v1.GetTeamMembersResponse
	(*models.User)(nil),            // 14: taskflow.models.v1.User
	(*models.Team)(nil),            // 15: taskflow.models.v1.Team
	(*models.TeamMember)(nil),      // 16: taskflow.models.v1.TeamMember
}
var file_user_api_user_proto_depIdxs = []int32{
	14, // 0: taskflow.user.v1.CreateUserResponse.user:type_name -> taskflow.models.v1.User
	14, // 1: taskflow.user.v1.GetUserResponse.user:type_name -> taskflow.models.v1.User
	14, // 2: taskflow.user.v1.UpdateUserResponse.user:type_name -> taskflow.models.v1.User
	15, // 3: taskflow.user.v1.CreateTeamResponse.team:type_name -> taskflow.models.v1.Team
	15, // 4: taskflow.user.v1.GetTeamResponse.team:type_name -> taskflow.models.v1.Team
	16, // 5: taskflow.user.v1.AddTeamMemberResponse.member:type_name -> taskflow.models.v1.TeamMember
	16, // 6: taskflow.user.v1.GetTeamMembersResponse.members:type_name -> taskflow.models.v1.TeamMember
	0,  // 7: taskflow.user.v1.UserService.CreateUser:input_type -> taskflow.user.v1.CreateUserRequest
	2,  // 8: taskflow.user.v1.UserService.GetUser:input_type -> taskflow.user.v1.GetUserRequest
	4,  // 9: taskflow.user.v1.UserService.UpdateUser:input_type -> taskflow.user.v1.UpdateUserRequest
	6,  // 10: taskflow.user.v1.UserService.CreateTeam:input_type -> taskflow.user.v1.CreateTeamRequest
	8,  // 11: taskflow.user.v1.UserService.GetTeam:input_type -> taskflow.user.v1.GetTeamRequest
	10, // 12: taskflow.user.v1.UserService.AddTeamMember:input_type -> taskflow.user.v1.AddTeamMemberRequest
	12, // 13: taskflow.user.v1.UserService.GetTeamMembers:input_type -> taskflow.user.v1.GetTeamMembersRequest
	1,  // 14: taskflow.user.v1.UserService.CreateUser:output_type -> taskflow.user.v1.CreateUserResponse
	3,  // 15: taskflow.user.v1.UserService.GetUser:output_type -> taskflow.user.v1.GetUserResponse
	5,  // 16: taskflow.user.v1.UserService.UpdateUser:output_type -> taskflow.user.v1.UpdateUserResponse
	7,  // 17: taskflow.user.v1.UserService.CreateTeam:output_type -> taskflow.user.v1.CreateTeamResponse
	9,  // 18: taskflow.user.v1.UserService.GetTeam:output_type -> taskflow.user.v1.GetTeamResponse
	11, // 19: taskflow.user.v1.UserService.AddTeamMember:output_type -> taskflow.user.v1.AddTeamMemberResponse
	13, // 20: taskflow.user.v1.UserService.GetTeamMembers:output_type -> taskflow.user.v1.GetTeamMembersResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_user_api_user_proto_init() }
func file_user_api_user_proto_init() {
	if File_user_api_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_api_user_proto_rawDesc), len(file_user_api_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_api_user_proto_goTypes,
		DependencyIndexes: file_user_api_user_proto_depIdxs,
		MessageInfos:      file_user_api_user_proto_msgTypes,
	}.Build()
	File_user_api_user_proto = out.File
	file_user_api_user_proto_goTypes = nil
	file_user_api_user_proto_depIdxs = nil
}
